### ISSUE TITLE
Problem with collector

### ISSUE THREAD

**Issue by wnowogrodzki** [samsonasik/SanSessionToolbar#20]
Hi, 

I've updated last version, and I get an error... 
```
Fatal error: Call to a member function getSessionData() on a non-object in /var/www/praca-eu/www/www/vendor/san/san-session-toolbar/src/SanSessionToolbar/Collector/SessionCollector.php on line 77
```

after 2 hours of debuging and searching I figured out that the problem is with serialization. Look at line 212 of ZendDeveloperTools/Profiler.php:

```
$this->report->addCollector(unserialize(serialize($collector)));
```

Before serialization - there is no problem - object SessionManager exists... cool, but after `unserialize(serialize())` SessionManager disapears. I don't know why. I checked - both classes exists.

Have you any idea what could be wrong?

**Comment by samsonasik** [comment]
I need info to reproduce your issue.
*1* . it seems you use SanSessionToolbar dev-master instead of 0.1.1, right ?
*2* . what ZendDeveloperTools you use ? 1.0.0-BETA5 or dev-master ?
*3* . what zf2 version you use ?
*4* . Any sample session data ?

**Comment by samsonasik** [comment]
@wnowogrodzki I've checked, the issue is it seems ZDT can't use collector that created via factory now. I will check it more deep or report issue in ZDT repo, could you try version 0.1.1 instead ? , it should still  work in version 0.1.1.

**Comment by wnowogrodzki** [comment]
Ok, thanks for reply. Previous version was fine and didn't generate any troubles.

**Comment by samsonasik** [comment]
I have fixed it with lazy load right now https://github.com/samsonasik/SanSessionToolbar/commit/1e443fdff9550e1c5d0e0bdf056926a9a0b78d3e .
