### ISSUE TITLE
Does not scroll

### ISSUE THREAD

**Issue by diemuzi** [samsonasik/SanSessionToolbar#32]
Just updated to the latest version and noticed the session container box does not have a scroll bar. This is actually important, see the screenshot:

![screenshot_1](https://cloud.githubusercontent.com/assets/1476204/8121365/87af0d36-1070-11e5-9c45-f6d0f2dac6bb.png)

There is a lot more information above that which I need to see =)

It would also be nice if each of those were on their own line instead of inline with each other until left-to-right runs out of room and then displays on another line.

**Comment by samsonasik** [comment]
in my side, the scroll works, but probably you can tell @wnowogrodzki as he was added this feature.
and about inline, could you install Xdebug? if you install it, you should can see like the following : 
![Fully Crud ZF2 sessions data](https://cloud.githubusercontent.com/assets/459648/6867548/cad28e40-d4b5-11e4-911c-ffd8b88fd41f.png)

**Comment by samsonasik** [comment]
ping @diemuzi could you elaborate my comment above ?

**Comment by diemuzi** [comment]
Xdebug is fine. Not sure what else I can do regarding the scroll not showing up properly. 


Sent via the Samsung Galaxy Note® 4

-------- Original message --------

**Comment by samsonasik** [comment]
based on your printscreen, it seems your xdebug doesn't work propertly, try turn on <code>html_errors = On</code> in php.ini and let see if the scroll will works or not.

**Comment by diemuzi** [comment]
I have xdebug disabled right now. Xdebug wasn't listed as a hard requirement and if that is the situation now, then we can close this bug as I'd prefer not to rely on it for a simple session container viewer. 


Sent via the Samsung Galaxy Note® 4

-------- Original message --------

**Comment by samsonasik** [comment]
xdebug is suggested, not required as I don't want it to be so hard to be used, and session data should be as little as possible.
