### ISSUE TITLE
SessionManager not found

### ISSUE THREAD

**Issue by pensiero** [samsonasik/SanSessionToolbar#34]
If I enable this module, I receive this error: http://jsfiddle.net/5rnr3uzj/
What could it be?

Thanks

**Comment by samsonasik** [comment]
you should use :
require : [
{
    "zendframework/zend-developer-tools": "dev-master"
}
]

as the collector uses factory which it serialized in old zendframework/zend-developer-tools, you have to use dev-master for that. Actually, zendframework/zend-developer-tools need new release :) 

Warm regards,

Abdul Malik Ikhsan

Pada 24 Jun 2015, pukul 21.55, Oscar Fanelli <notifications@github.com> menulis:

**Comment by pensiero** [comment]
:+1: 
@ocramius, gogogo :D we all know that you're doing nothing! loafer! :stuck_out_tongue_winking_eye: :stuck_out_tongue_winking_eye: :stuck_out_tongue_winking_eye:

**Comment by samsonasik** [comment]
https://twitter.com/samsonasik/status/613724564808294400 ;)

**Comment by samsonasik** [comment]
I'm closing it then ;)

**Comment by pensiero** [comment]
:+1:
