### ISSUE TITLE
Install SanSessionToolbar without composer

### ISSUE THREAD

**Issue by vbogoev** [samsonasik/SanSessionToolbar#37]
Hellom

is it possible to install SanSessionToolbar without composer? When I try I'm getting error: "Module (SanSessionToolbar) could not be initialized."

Best Regards!

**Comment by samsonasik** [comment]
No, sorry ;). If you don't have shell access, you can install via http://composer.borreli.com paste your composer.json there, and download. Don't forget to add "san/san-session-toolbar": "0.*"
