### ISSUE TITLE
"Base Href" problem

### ISSUE THREAD

**Issue by guliano** [samsonasik/SanSessionToolbar#39]
Hello,

In my project I have following tag in the layout:
```html
<base href="/src/" />
```

Then in the Session Toolbar all links go via http://localhost/src/san-session-toolbar/* which is not valid.
It would be nice to specify in the config `base_url` for the toolbar links.

**Comment by samsonasik** [comment]
@Stanimirdim92 could you verify it? seems related with your html change?

**Comment by Stanimirdim92** [comment]
The base tag is used to append anyting at the start of the url. Id i have a
website mysite.com and add /example.com in that base tag, all <a> tags will
have in their hrefs /example.com/mysite.com. I dont remember adding this
when i tags refactored the code. Simply remove it and everything will be
fine.

Im away from pc atm so i cant test it. If you can wait until tonight ok.
На 30.10.2015 12:37 "Abdul Malik Ikhsan" <notifications@github.com> написа:

**Comment by Stanimirdim92** [comment]
Just checkeck all html in the module and i couldnt fine any base tag. Since the base tag needs to be in the head i assume its in your app.

**Comment by guliano** [comment]
Yes it is in my app, as I said. And this is a problem. I need this tag for the static resources. But all my api endpoints just go without this tag and this is ok. Only SessionToolbar is appending this. So my question is, can we add this to config what `base_url` should be used for the toolbar links?

**Comment by Stanimirdim92** [comment]
I think we can will create a test tonight or tomorrow

**Comment by guliano** [comment]
Sure, thanks for your time

**Comment by samsonasik** [comment]
@guliano I tried `<base href="/src/" />` in both layout and view, and everything ok, are you sure it because of it ?

**Comment by Stanimirdim92** [comment]
Just tested it on my CMS. I can see /src/ in the url. However, all buttons from the module works fine. Can you post your layout.phtml file and your document structure?

**Comment by guliano** [comment]
Hmm, I think I figured it out. It is not a problem with only base tag, but with config in view_manager. I have something like this in the config:

```php
'view_manager' => array(
    'base_path' => '/src/',
),
```

And in layout I have:
```html
<base href="<?= $this->basePath() ?>" />
```

This is causing the problem what I mentioned. If I only set 
```html
<base href="/src/" />
```
without setting a `base_path` in the view_manager config everything is ok.

**Comment by samsonasik** [comment]
closable then?

**Comment by Stanimirdim92** [comment]
DOn't think so. WIll debug later. Just came home...

**Comment by guliano** [comment]
No, because I think this is a bug. If I want to setup this `base_path` via `view_manager` config and then links on the session toolbar does not work.
See [this repository](https://github.com/guliano/sessiontest) as example.

I set the `base_path` in the config in Application module. If I remove this, links in the toolbar works.
In my application case I have following setup:
`base_path = '/src/'` for the development assets and `base_path = '/dist/'` for the production assets. I control this via configuration loaded depending on the environment.

Could you take a look for this, and try to solve it? I think it could be solved by an additional configuration key, for example:
```php
'session-toolbar' => [
    'base_path' => '',
]
```
with empty string as default. It should solve the problem.

**Comment by samsonasik** [comment]
https://github.com/samsonasik/SanSessionToolbar/pull/41 is a PR for it

**Comment by samsonasik** [comment]
Fixes in #42 ;)

**Comment by guliano** [comment]
Awesome. Thank you :)

**Comment by samsonasik** [comment]
please do composer update ;)

**Comment by samsonasik** [comment]
@guliano fixes should be on `0.2.2` tag, if you got `0.2.1`, remove your composer.lock and re-run composer update ;)

**Comment by guliano** [comment]
You did mistake in id here:
https://github.com/samsonasik/SanSessionToolbar/blob/fae00c707b65828cd9de48b1a18cdff16874e806/view/zend-developer-tools/toolbar/session-toolbar.js#L35

**Comment by samsonasik** [comment]
@guliano yes, i have just done a fixes for it ;), please remove your composer.lock and re-run composer update ;), should be fixed in `0.2.2` release ;)

**Comment by samsonasik** [comment]
fixes in https://github.com/samsonasik/SanSessionToolbar/commit/a8cb9496ce61e518ec3260ae4b901db2034c6925 and tag new release `0.2.2` , you can remove composer.lock and re-run composer update ;)

**Comment by guliano** [comment]
Confirmed. Now it works as intended. Fix for fix is ok :)
