### ISSUE TITLE
Could not be initialited

### ISSUE THREAD

**Issue by andrconstruction** [samsonasik/SanSessionToolbar#43]
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (SanSessionToolbar) could not be initialized.' in 
I see this error during enabled the toolbar

this is my config 

$env = getenv( 'APP_ENV' ) ?: 'production';

	$modules = [
		'AssetsBundle',
		'Application',
		'User',
		'Firm',
		'Unit',
		'Kbase',
		'SCatalog',
		'Claim',
		'Auth',
		'Dep',
		'Exam',
		'DoctrineModule',
		'DoctrineORMModule',
		'Soflomo\Purifier',
		

	];
	if ( $env == 'development' ) {
		$modules[] = 'ZendDeveloperTools';
		$modules[] = 'SanSessionToolbar';
		$modules[] = 'BjyProfiler';
	}

**Comment by samsonasik** [comment]
you need to install via composer, please read the readme.

**Comment by andrconstruction** [comment]
Of course I installed it via composer

**Comment by samsonasik** [comment]
run in shell: `composer update`, check if the module installed in `vendor/san`, if you don't have command line access, install via web interface by copying your compsoer.json in http://composer.borreli.com/

**Comment by andrconstruction** [comment]
updated, no new files
module installed in  vendor/san  - verified

**Comment by samsonasik** [comment]
san-session-toolbar folder should be in vendor/san ,  try remove vendor folder, remove composer.lock, and run composer install

**Comment by andrconstruction** [comment]
> "C:\Program Files (x86)\PHP\php.exe" D:\_workSites\claim\z\composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing san/san-session-toolbar (0.2.2)
    Loading from cache

san/san-session-toolbar suggests installing ext-xdebug (For better output format of session data, Xdebug should already installed)
Writing lock file
Generating autoload files

after uploaded to server and no effect the same error

**Comment by andrconstruction** [comment]
![filo](https://cloud.githubusercontent.com/assets/7435330/10877915/6c6c2d5e-815b-11e5-981b-33944d5f21e4.png)

On server

**Comment by andrconstruction** [comment]
Perhaps I have to do something in configs zdt or somewhere else

**Comment by samsonasik** [comment]
just re-check the autoloader, remove vendor/ folder in uploaded server, re-upload all files in vendor/ folder. Also, check if your zfskeleton uses composer for autoloader, usually in init_autoloader.php

Warm regards,

Abdul Malik Ikhsan

Pada 2 Nov 2015, pukul 16.18, andrconstruction <notifications@github.com> menulis:
