### ISSUE TITLE
[docs] ZF3 Missing flash messenger plugin

### ISSUE THREAD

**Issue by xorock** [samsonasik/SanSessionToolbar#55]
For ZF3 there is no require section in composer.json for "zendframework/zend-mvc-plugin-flashmessenger": "^1.0"

Perhaps it is worth mentioning in the documentation that plugin is required for proper operation?

**Comment by samsonasik** [comment]
should be on "suggest" section in composer.json, wanna create a PR about it?

Thank you.

Warm regards,

Abdul Malik Ikhsan

Pada 28 Agt 2016, pukul 20.08, xorock <notifications@github.com> menulis:

**Comment by samsonasik** [comment]
the code itself in Module.php needs check if service has plugin named 'flashMessenger'

Warm regards,

Abdul Malik Ikhsan

Pada 28 Agt 2016, pukul 20.08, xorock <notifications@github.com> menulis:

**Comment by samsonasik** [comment]
@xorock fixed at https://github.com/samsonasik/SanSessionToolbar/commit/d4911c650733b5a328ed6e47825277af46db9953 , Thank you for the report ;)
