### ISSUE TITLE
Suggestion: make SanSessionToolbar installable via Zend\ComponentInstaller

### ISSUE THREAD

**Issue by RalfEggert** [samsonasik/SanSessionToolbar#58]
I would like to suggest, to make `SanSessionToolbar` installable via the `Zend\ComponentInstaller`. I think it is only needed to add some configuration to the `composer.json` file to get this handled automatically.

This is from the `composer.json` file of `ZendDeveloperTools`:

```
    "extra": {
        "zf": {
            "module": "ZendDeveloperTools"
        }
    },
```

@samsonasik I hope you are much quicker to add this than me having to fork the project and sending a PR.

**Comment by samsonasik** [comment]
it seems not possible if it not registered at `ZendSkeletonApplication` as well: https://github.com/zendframework/ZendSkeletonApplication/blob/master/composer.json#L34

**Comment by samsonasik** [comment]
I tried with #59 but not possible as the module injected as first row of `config/modules.config.php`, while it depends on `ZendDeveloperTools`

**Comment by samsonasik** [comment]
#59 re-open, I tried in another modules i have, after module tagged, it inserted into last of the module list.

**Comment by samsonasik** [comment]
still not possible after tag it, it keep added into first row.

**Comment by RalfEggert** [comment]
Ok, I didn't thought it would be so complicated. I noticed that the config for a component and a module is slightly different and that `ZendDeveloperTools` is always added to the bottom while for example `Zend\Session` is added to the top of the modules list when installed by the `Zend\ComponentInstaller`:

Please compare
- https://github.com/zendframework/ZendDeveloperTools/blob/master/composer.json
- https://github.com/zendframework/zend-session/blob/master/composer.json

Does that help solving the issue? If `SanSessionToolbar` depends on `ZendDeveloperTools` maybe the installer handles the order automatically?

**Comment by samsonasik** [comment]
I'm not understand, maybe you can create PR and try to composer require yourself, if everything works, I will happy to merge

**Comment by RalfEggert** [comment]
@samsonasik 

I just saw that you used the `extra -> zf -> module` configuration already in your commits. That would be the way I would try it. Sad, that it doesn't work. I guess the problem must be in the `Zend\ComponentInstaller` then. Maybe I find some time to play around with it in the near future. But currently time is very limited....

**Comment by samsonasik** [comment]
Thank you, if you want to try existing commit ( which reverted in next commit ), you can try:
```
composer require san/san-session-toolbar:dev-master#14b86ea950cfbfc43c4e243a34dee35d2e5bd37e
```
