### ISSUE TITLE
Session toolbar does not support name of session container with \

### ISSUE THREAD

**Issue by 0kph** [samsonasik/SanSessionToolbar#63]
If name of session container contains char \ (eg: 'Foo\Bar' ) "Add new session data" and "Edit session data" inside this container generate errors

`Uncaught TypeError: Cannot read property 'style' of null at HTMLAnchorElement.addNewSessionData`
`Line: 2084: doc.querySelector("#san-session-toolbar-info-add-new-data-containerName-"+containerName).style.display = 'block';`

`Uncaught TypeError: Cannot read property 'style' of null at HTMLAnchorElement.editSessionByKey`
`Line 2019: doc.querySelector("#san-session-toolbar-info-containerName-"+containerName+"-keysession-"+keysession).style.display = 'none';`

It works fine when You change Foo\Bar to Foo_Bar.

**Comment by samsonasik** [comment]
@Stanimirdim92 could you take a look on this? Thanks ;)

**Comment by samsonasik** [comment]
@0kph it has been fixed at https://github.com/samsonasik/SanSessionToolbar/commit/945367a9b2ab4b9ab1a8ce28a58a35c717e0517e and tagged 1.0.7 for it. Please composer update. Thank you ;)
