### ISSUE TITLE
Adding additional identifiers to eventmanager causes error

### ISSUE THREAD

**Issue by tnrn9b** [samsonasik/SanSessionToolbar#82]
If additional event identifiers other than Laminas\Mvc\Application get added to the event manager, the flash messenger function in the project's Module.php causes an error to be thrown because it no longer picks out the Laminas\Mvc\Application instance. I'll recreate the issue and post code. If I create a solution would you want a pull request?

**Comment by samsonasik** [comment]
Yes please. Thank you.

**Comment by tnrn9b** [comment]
Recreating issue:

in Module.php of a main project:

```
public function onBootstrap(MvcEvent $event)
{
        ...
        /** @var EventManager $events */
        $events   = $event->getApplication()->getEventManager();
        $events->addIdentifiers([AbstractActionController::class]);
       ...
}
```

This is enough to cause the error.

**Comment by samsonasik** [comment]
closing. ref https://github.com/samsonasik/SanSessionToolbar/pull/83#issuecomment-617684545
