### ISSUE TITLE
Deprecation of the Serializable interface in PHP 8.1

### ISSUE THREAD

**Issue by Koen1999** [samsonasik/SanSessionToolbar#87]
`Deprecated: SanSessionToolbar\Collector\SessionCollector implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /code/vendor/san/san-session-toolbar/src/Collector/SessionCollector.php on line 0`

**Comment by samsonasik** [comment]
It waits for laminas-developer-tools's `AbstractCollector` update https://github.com/laminas/laminas-developer-tools/pull/41

**Comment by samsonasik** [comment]
laminas-developer-tools 2.3.0 released for it https://github.com/laminas/laminas-developer-tools/releases/tag/2.3.0

I am closing it.
